oca:
  - account-analytic
  - account-closing
  - account-financial-reporting
  - account-financial-tools
  - account-fiscal-rule
  - account-invoice-reporting
  - account-invoicing
  - account-payment
  - account-reconcile
  - bank-payment
  - bank-statement-import
  - brand
  - calendar
  - community-data-files
  - connector
  - connector-ecommerce
  - connector-prestashop
  - connector-telephony
  - contract
  - credit-control
  - crm
  - currency
  - data-protection
  - delivery-carrier
  - dms
  - e-commerce
  - edi
  - hr
  - knowledge
  - timesheet
  - intrastat-extrastat
  - l10n-france
  - l10n-brazil
  - manufacture
  - mis-builder
  - multi-company
  - partner-contact
  - pos
  - product-attribute
  - product-variant
  - project
  - project-reporting
  - purchase-reporting
  - purchase-workflow
  - queue
  - reporting-engine
  - rest-framework
  - rma
  - sale-financial
  - sale-reporting
  - sale-workflow
  - currency
  - search-engine
  - server-auth
  - server-backend
  - server-brand
  - server-env
  - server-tools
  - server-ux
  - social
  - stock-logistics-barcode
  - stock-logistics-reporting
  - stock-logistics-tracking
  - stock-logistics-warehouse
  - stock-logistics-workflow
  - storage
  - support
  - web
  - web-api
  - wms
akretion:
  - account-move-import
  - bank-statement-reconcile-simple
  - ak-odoo-incubator
  - odoo-usability
  - odoo-import-helper
  - odoo-perf
  - partner-module-information
  - pos-sale-order
  - profiloo
  - sale-configurator
  - rest-authenticable
  - odoo-mooncard-connector
  - subcontractor
  - odoo-py3o-report-templates
shopinvader:
  - pattern-import-export
  - odoo-shopinvader
  - odoo-shopinvader-payment
forgeflow:
  - stock-rma
