oca:
  - account-financial-reporting
#  - account-financial-tools
#  - account-fiscal-rule
#  - account-invoice-reporting
#  - account-invoicing
#  - account-payment
#  - account-reconcile
#  - bank-payment
#  - bank-statement-import
#  - community-data-files
#  - connector
#  - connector-ecommerce
#  - connector-telephony
#  - contract
#  - crm
#  - delivery-carrier
#  - e-commerce
#  - edi
#  - hr
#  - hr-timesheet
#  - intrastat
#  - l10n-france
#  - l10n-brazil
#  - manufacture
#  - partner-contact
#  - pos
#  - product-attribute
#  - product-variant
#  - project
#  - project-reporting
#  - purchase-reporting
#  - purchase-workflow
#  - reporting-engine
#  - mis-builder
#  - sale-financial
#  - sale-reporting
#  - sale-workflow
#  - currency
#  - search-engine
#  - server-auth
#  - server-backend
#  - server-brand
#  - server-env
#  - server-tools
#  - server-ux
#  - social
#  - stock-logistics-barcode
#  - stock-logistics-reporting
#  - stock-logistics-warehouse
#  - stock-logistics-workflow
#  - web
akretion:
  - ak-odoo-incubator
  - odoo-usability

