akretion:
- account-move-import
- bank-statement-reconcile-simple
- ak-odoo-incubator
- odoo-usability
- odoo-import-helper
- odoo-perf
- partner-module-information
- pos-sale-order
- profiloo
- sale-configurator
- rest-authenticable
- odoo-mooncard-connector
- subcontractor
- odoo-py3o-report-templates
forgeflow:
- stock-rma
oca:
- account-analytic
- account-budgeting
- account-closing
- account-consolidation
- account-financial-reporting
- account-financial-tools
- account-fiscal-rule
- account-invoice-reporting
- account-invoicing
- account-payment
- account-reconcile
- agreement
- apps-store
- automation
- bank-payment
- bank-statement-import
- brand
- business-requirement
- calendar
- commission
- community-data-files
- connector
- connector-accountedge
- connector-cmis
- connector-ecommerce
- connector-infor
- connector-interfaces
- connector-jira
- connector-lengow
- connector-lims
- connector-magento
- connector-odoo2odoo
- connector-prestashop
- connector-redmine
- connector-sage
- connector-salesforce
- connector-spscommerce
- connector-telephony
- connector-woocommerce
- contract
- cooperative
- credit-control
- crm
- currency
- data-protection
- ddmrp
- delivery-carrier
- department
- dms
- donation
- dotnet
- e-commerce
- e-learning
- edi
- edi-framework
- event
- field-service
- fleet
- geospatial
- helpdesk
- hr
- hr-attendance
- hr-expense
- hr-holidays
- infrastructure
- interface-github
- intrastat-extrastat
- iot
- knowledge
- l10n-brazil
- l10n-france
- maintenance
- management-system
- manufacture
- manufacture-reporting
- margin-analysis
- mis-builder
- mis-builder-contrib
- multi-company
- oca-custom
- odoo-pim
- operating-unit
- partner-contact
- payroll
- pms
- pos
- product-attribute
- product-configurator
- product-kitting
- product-pack
- product-variant
- program
- project
- project-agile
- project-reporting
- purchase-reporting
- purchase-workflow
- pwa-builder
- queue
- repair
- report-print-send
- reporting-engine
- resource
- rest-api
- rest-framework
- rma
- role-policy
- runbot-addons
- sale-channel
- sale-financial
- sale-promotion
- sale-reporting
- sale-workflow
- search-engine
- server-auth
- server-backend
- server-brand
- server-env
- server-tools
- server-ux
- shift-planning
- sign
- social
- spreadsheet
- stock-logistics-availability
- stock-logistics-barcode
- stock-logistics-interfaces
- stock-logistics-orderpoint
- stock-logistics-reporting
- stock-logistics-request
- stock-logistics-tracking
- stock-logistics-transport
- stock-logistics-warehouse
- stock-logistics-workflow
- stock-weighing
- storage
- survey
- timesheet
- vertical-abbey
- vertical-agriculture
- vertical-association
- vertical-community
- vertical-construction
- vertical-cooperative-supermarket
- vertical-edition
- vertical-education
- vertical-hotel
- vertical-isp
- vertical-medical
- vertical-ngo
- vertical-realestate
- vertical-rental
- vertical-travel
- wallet
- web
- web-api
- web-api-contrib
- webhook
- webkit-tools
- website
- website-cms
- website-themes
- wms
shopinvader:
- pattern-import-export
- odoo-shopinvader
- odoo-shopinvader-payment
